version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      production-dependecies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"